### PR TITLE
Update to 5.3.10.

### PR DESCRIPTION
**Pull request by cdaringe**
5.3.5 fails on `preg_match`s.  And im in big trouble because of it! :$

### CODE REVIEW

**Comment by ikkez** [comment]
what preg_match's should that be? We tested most parts on 5.3.3. The jump to 5.3.5 was just about some interator references, but the rest should work, as long as PCRE 8.02 or higher is available (for the regex stuff)

**Comment by cdaringe** [comment]
really the preg_match's *silently fail* by not matching full well. Actually, the change probably hit in 5.3.6 or 5.3.7? http://php.net/ChangeLog-5.php#5.3.6

I didn't have a change to try these incremental versions--I did have the chance to test on 5.3.10

**Comment by xfra35** [comment]
The changelog talks about a preg_match fix in 5.3.4, not in 5.3.6..

Can you tell which exact preg_match failed? From what you describe (*all* preg_match), it looks like you're running an old PCRE version. For example, horizontal tabs `\h` have been introduced in 7.2, so running an older PCRE version would fail *a lot of* preg_match.

**Comment by cdaringe** [comment]
sure. apologies for the lack or information posted before hand.  i know better.  panic mode ensued when pushing to production.  anyway, here was a simple test I ran between my two versions.

```php
$pattern = "GET /v1/study";
$types = array("ajax", "async");
preg_match('/([\|\w]+)\h+(?:(?:@(\w+)\h*:\h*)?([^\h]+)|@(\w+))(?:\h+\[('.implode('|',$types).')\])?/',$pattern,$parts);
print_r($parts); // in 5.3.5 empty array observed. in 5.3.10, populated array observed
```

this originated from the `route` function in `base.php` (below is the diff how I shadily hacked it to make it work with my install temporarily)

```diff
    function route($pattern,$handler,$ttl=0,$kbps=0) {
        $types=array('sync','ajax');
-       if (is_array($pattern)) {
-           foreach ($pattern as $item)
-               $this->route($item,$handler,$ttl,$kbps);
-           return;
-       }
-       preg_match('/([\|\w]+)\h+(?:(?:@(\w+)\h*:\h*)?([^\h]+)|@(\w+))'.
-           '(?:\h+\[('.implode('|',$types).')\])?/',$pattern,$parts);
-       if ($parts[2])
-           $this->hive['ALIASES'][$parts[2]]=$parts[3];
-       elseif (!empty($parts[4])) {
-           if (empty($this->hive['ALIASES'][$parts[4]]))
-               user_error(sprintf(self::E_Named,$parts[4]));
-           $parts[3]=$this->hive['ALIASES'][$parts[4]];
-       }
-       if (empty($parts[3]))
+        $urlPos = strpos($pattern, '/');
+        $actions = trim(substr($pattern, 0, $urlPos));
+        $url = trim(substr($pattern, $urlPos));
+       if (empty($url))
            user_error(sprintf(self::E_Pattern,$pattern));
        $type=empty($parts[5])?
            self::REQ_SYNC|self::REQ_AJAX:
            constant('self::REQ_'.strtoupper($parts[5]));
-       foreach ($this->split($parts[1]) as $verb) {
+       foreach ($this->split($actions) as $verb) {
            if (!preg_match('/'.self::VERBS.'/',$verb))
                $this->error(501,$verb.' '.$this->hive['URI']);
-           $this->hive['ROUTES'][str_replace('@',"\x00".'@',$parts[3])]
+           $this->hive['ROUTES'][str_replace('@',"\x00".'@',$url)]
                [$type][strtoupper($verb)]=array($handler,$ttl,$kbps);
        }
    }
```

**Comment by ikkez** [comment]
are you running CentOS? please check the PCRE version in phpinfo();
Here you have a php 5.3.5 installation, running F3 3.4.1-dev... no problems with the routing: http://46.38.240.89/f3/router

**Comment by xfra35** [comment]
Even with [PHP 5.2.16](http://sandbox.onlinephpfunctions.com/code/8e07cd6adbe82a48cc2f887dbfe2bcce0c94a92e) this preg_match works ;)

Really, when it comes to regex, the PCRE version tells more than the PHP one.

**Comment by cdaringe** [comment]
Yep, CentOS.
PCRE `6.6 06-Feb-2006`
:frowning:

is it worth changing my README update to denote that?  what are your thoughts?

**Comment by ikkez** [comment]
The page about system requirements, linked on the home page, http://fatfreeframework.com/system-requirements and some paragraphs below your change, already clearifies about it. Maybe the CentOS warning is not big enough :smile:

**Comment by cdaringe** [comment]
well that's super embarrassing. :/  sorry guys.  sheesh, can't believe i missed all of that

**Pull request closed without merging**
